/* Automatically generated by './build/bin/build-entry.js' */
import ElementUI from 'element-ui';
import Btn from '../packages/btn/index.js';
const components = [
  Btn
];

const install = function(Vue, opts = {}) {
  Vue.use(ElementUI, {...opts});
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.1.8',
  install,
  Btn
};
